In [27]:
from nba_api.stats.endpoints import leaguedashplayerstats

player_stats = leaguedashplayerstats.LeagueDashPlayerStats(per_mode_detailed="PerGame")
df = player_stats.get_data_frames()[0]

print(df.shape)
print(df.columns)
print(df.isnull().sum())
df.head()

(24, 66)
Index(['PLAYER_ID', 'PLAYER_NAME', 'NICKNAME', 'TEAM_ID', 'TEAM_ABBREVIATION',
       'AGE', 'GP', 'W', 'L', 'W_PCT', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M',
       'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST',
       'TOV', 'STL', 'BLK', 'BLKA', 'PF', 'PFD', 'PTS', 'PLUS_MINUS',
       'NBA_FANTASY_PTS', 'DD2', 'TD3', 'WNBA_FANTASY_PTS', 'GP_RANK',
       'W_RANK', 'L_RANK', 'W_PCT_RANK', 'MIN_RANK', 'FGM_RANK', 'FGA_RANK',
       'FG_PCT_RANK', 'FG3M_RANK', 'FG3A_RANK', 'FG3_PCT_RANK', 'FTM_RANK',
       'FTA_RANK', 'FT_PCT_RANK', 'OREB_RANK', 'DREB_RANK', 'REB_RANK',
       'AST_RANK', 'TOV_RANK', 'STL_RANK', 'BLK_RANK', 'BLKA_RANK', 'PF_RANK',
       'PFD_RANK', 'PTS_RANK', 'PLUS_MINUS_RANK', 'NBA_FANTASY_PTS_RANK',
       'DD2_RANK', 'TD3_RANK', 'WNBA_FANTASY_PTS_RANK'],
      dtype='object')
PLAYER_ID                0
PLAYER_NAME              0
NICKNAME                 0
TEAM_ID                  0
TEAM_ABBREVIATION        0
                        ..
PLUS_MINUS_RANK          0
NBA_FANTASY_PTS_RANK     0
DD2_RANK                 0
TD3_RANK                 0
WNBA_FANTASY_PTS_RANK    0
Length: 66, dtype: int64

,PLAYER_ID,PLAYER_NAME,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP,W,L,W_PCT,...,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,WNBA_FANTASY_PTS_RANK
0,1630162,Anthony Edwards,Anthony,1610612750,MIN,21.0,1,0,1,0.0,...,4,4,6,5,10,19,16,5,1,15
1,1628389,Bam Adebayo,Bam,1610612748,MIA,25.0,1,1,0,1.0,...,4,4,6,5,19,16,22,5,1,22
2,203081,Damian Lillard,Damian,1610612757,POR,32.0,1,1,0,1.0,...,4,4,6,5,6,8,6,5,1,6
3,1628368,De'Aaron Fox,De'Aaron,1610612758,SAC,25.0,1,0,1,0.0,...,4,4,6,5,24,9,23,5,1,23
4,201942,DeMar DeRozan,DeMar,1610612741,CHI,33.0,1,1,0,1.0,...,4,4,6,5,14,7,10,5,1,10

In [28]:
df = df[['PLAYER_ID', 'PLAYER_NAME', 'NICKNAME', 'TEAM_ABBREVIATION', 'GP', 'MIN', 'PTS', 'REB', 'AST', 'STL', 'BLK', 'FG_PCT', 'FT_PCT', 'FG3_PCT', 'FG3A']]
# df = df[(df['GP'] > 30)]
df = df.sort_values('FG3A', ascending=False)
print(df["TEAM_ABBREVIATION"].unique())
df.head()

['POR' 'BOS' 'CLE' 'LAC' 'PHI' 'DAL' 'UTA' 'IND' 'NYK' 'LAL' 'MIL' 'MIN'
 'MEM' 'DEN' 'TOR' 'OKC' 'MIA' 'SAC' 'CHI']

,PLAYER_ID,PLAYER_NAME,NICKNAME,TEAM_ABBREVIATION,GP,MIN,PTS,REB,AST,STL,BLK,FG_PCT,FT_PCT,FG3_PCT,FG3A
2,203081,Damian Lillard,Damian,POR,1,23.4,26.0,3.0,4.0,3.0,0.0,0.429,0.0,0.400,20.0
11,1628369,Jayson Tatum,Jayson,BOS,1,35.3,55.0,10.0,6.0,1.0,1.0,0.710,0.5,0.556,18.0
6,1628378,Donovan Mitchell,Donovan,CLE,1,30.1,40.0,4.0,10.0,3.0,0.0,0.600,1.0,0.471,17.0
10,1627759,Jaylen Brown,Jaylen,BOS,1,25.2,35.0,14.0,5.0,2.0,0.0,0.593,0.0,0.250,12.0
21,202331,Paul George,Paul,LAC,1,17.9,8.0,2.0,2.0,1.0,1.0,0.308,0.0,0.000,9.0

In [29]:
df.to_csv('player_data.csv', index=False)