In [12]:
from nba_api.stats.endpoints import leaguedashplayerstats

player_stats = leaguedashplayerstats.LeagueDashPlayerStats(per_mode_detailed="PerGame")
df = player_stats.get_data_frames()[0]

print(df.shape)
print(df.columns)
print(df.isnull().sum())
df.head()

(539, 66)
Index(['PLAYER_ID', 'PLAYER_NAME', 'NICKNAME', 'TEAM_ID', 'TEAM_ABBREVIATION',
       'AGE', 'GP', 'W', 'L', 'W_PCT', 'MIN', 'FGM', 'FGA', 'FG_PCT', 'FG3M',
       'FG3A', 'FG3_PCT', 'FTM', 'FTA', 'FT_PCT', 'OREB', 'DREB', 'REB', 'AST',
       'TOV', 'STL', 'BLK', 'BLKA', 'PF', 'PFD', 'PTS', 'PLUS_MINUS',
       'NBA_FANTASY_PTS', 'DD2', 'TD3', 'WNBA_FANTASY_PTS', 'GP_RANK',
       'W_RANK', 'L_RANK', 'W_PCT_RANK', 'MIN_RANK', 'FGM_RANK', 'FGA_RANK',
       'FG_PCT_RANK', 'FG3M_RANK', 'FG3A_RANK', 'FG3_PCT_RANK', 'FTM_RANK',
       'FTA_RANK', 'FT_PCT_RANK', 'OREB_RANK', 'DREB_RANK', 'REB_RANK',
       'AST_RANK', 'TOV_RANK', 'STL_RANK', 'BLK_RANK', 'BLKA_RANK', 'PF_RANK',
       'PFD_RANK', 'PTS_RANK', 'PLUS_MINUS_RANK', 'NBA_FANTASY_PTS_RANK',
       'DD2_RANK', 'TD3_RANK', 'WNBA_FANTASY_PTS_RANK'],
      dtype='object')
PLAYER_ID                0
PLAYER_NAME              0
NICKNAME                 0
TEAM_ID                  0
TEAM_ABBREVIATION        0
                        ..
PLUS_MINUS_RANK          0
NBA_FANTASY_PTS_RANK     0
DD2_RANK                 0
TD3_RANK                 0
WNBA_FANTASY_PTS_RANK    0
Length: 66, dtype: int64

,PLAYER_ID,PLAYER_NAME,NICKNAME,TEAM_ID,TEAM_ABBREVIATION,AGE,GP,W,L,W_PCT,...,BLK_RANK,BLKA_RANK,PF_RANK,PFD_RANK,PTS_RANK,PLUS_MINUS_RANK,NBA_FANTASY_PTS_RANK,DD2_RANK,TD3_RANK,WNBA_FANTASY_PTS_RANK
0,1630639,A.J. Lawson,A.J.,1610612742,DAL,22.0,15,5,10,0.333,...,491,358,475,457,429,462,482,253,39,466
1,1631260,AJ Green,AJ,1610612749,MIL,23.0,35,27,8,0.771,...,491,498,454,518,392,309,455,253,39,436
2,1631100,AJ Griffin,AJ,1610612737,ATL,19.0,72,34,38,0.472,...,372,268,394,422,217,169,287,253,39,273
3,203932,Aaron Gordon,Aaron,1610612743,DEN,27.0,68,45,23,0.662,...,65,32,205,58,82,4,77,56,39,89
4,1628988,Aaron Holiday,Aaron,1610612737,ATL,26.0,63,32,31,0.508,...,345,315,377,356,415,212,413,253,39,416

In [16]:
df = df[['PLAYER_NAME', 'TEAM_ABBREVIATION', 'GP', 'PTS', 'REB', 'AST', 'STL', 'BLK', 'FG_PCT', 'FT_PCT', 'FG3_PCT']]
df = df.sort_values('PTS', ascending=False)
print(df["TEAM_ABBREVIATION"].unique())
df.head()

['PHI' 'DAL' 'POR' 'OKC' 'MIL' 'BOS' 'GSW' 'PHX' 'LAL' 'CLE' 'MEM' 'ATL'
 'NOP' 'UTA' 'NYK' 'SAC' 'CHI' 'MIN' 'DEN' 'TOR' 'LAC' 'CHA' 'WAS' 'MIA'
 'HOU' 'SAS' 'DET' 'IND' 'BKN' 'ORL']

,PLAYER_NAME,TEAM_ABBREVIATION,GP,PTS,REB,AST,STL,BLK,FG_PCT,FT_PCT,FG3_PCT
252,Joel Embiid,PHI,66,33.1,10.2,4.2,1.0,1.7,0.548,0.857,0.330
341,Luka Doncic,DAL,66,32.4,8.6,8.0,1.4,0.5,0.496,0.742,0.342
90,Damian Lillard,POR,58,32.2,4.8,7.3,0.9,0.3,0.463,0.914,0.371
463,Shai Gilgeous-Alexander,OKC,68,31.4,4.8,5.5,1.6,1.0,0.510,0.905,0.345
166,Giannis Antetokounmpo,MIL,63,31.1,11.8,5.7,0.8,0.8,0.553,0.645,0.275